"""create tables

Revision ID: bcb7a3300e60
Revises: 6f5d34447294
Create Date: 2025-02-20 21:25:28.629417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcb7a3300e60'
down_revision: Union[str, None] = '6f5d34447294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imagenes_medicas', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_imagenes_medicas_region_anatomica'), 'imagenes_medicas', ['region_anatomica'], unique=False)
    op.create_index(op.f('ix_imagenes_medicas_tipo_imagen'), 'imagenes_medicas', ['tipo_imagen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagenes_medicas_tipo_imagen'), table_name='imagenes_medicas')
    op.drop_index(op.f('ix_imagenes_medicas_region_anatomica'), table_name='imagenes_medicas')
    op.alter_column('imagenes_medicas', 'data',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
