"""create tables

Revision ID: 018caa7c8768
Revises: 8d381d454300
Create Date: 2025-02-20 11:02:41.227656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018caa7c8768'
down_revision: Union[str, None] = '8d381d454300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenes_medicas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tipo_imagen', sa.String(), nullable=False),
    sa.Column('region_anatomica', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenes_medicas_id'), 'imagenes_medicas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagenes_medicas_id'), table_name='imagenes_medicas')
    op.drop_table('imagenes_medicas')
    # ### end Alembic commands ###
