@startuml

skinparam componentStyle uml2

package "'AlmacenamientoDeImagenes' Core Domain" <<Rectangle>> {
	class ImagenAlmacenada <<(E,DarkSeaGreen) Entity>> {
		String idImagen
		String ubicacion
		String fechaAlmacenamiento
	}
}
legend left
  This subdomain is part of the 'AnonimizacionYAlmacenamientoDeImagenes' domain.

  Almacenar imágenes de manera segura y accesible.
end legend


@enduml
